### PR TITLE
Updating README...

### PR DESCRIPTION
**Pull request by dossan**
I have changed just the style of the README file, in order to possibly make it more readable ;)

### CODE REVIEW

**Comment by pombredanne** [comment]
thanks!

**Comment by dossan** [comment]
No problem. Would it be possible to port this code to Python 3?

**Comment by pombredanne** [comment]
@dossan sure, go for it!
I suggest porting first to Python 2.7... once on 2.7, 3 is mostly automated

**Comment by pombredanne** [comment]
Check also other forks such as https://github.com/pombredanne/grailbrowser/compare/master...MaxMorais:master that has some ports done already ... I can pull these in if they merge easy

**Comment by dossan** [comment]
I would like to have a lot of time to go through the source and check for possible problem when converting... I will see what I can dot. Ideally, it should be the original creators to do it, because they know better than others the structure...

**Comment by dossan** [comment]
Also, why is there no `Issues` section for this repository? (Or am I blind?)

**Comment by vadmium** [comment]
Hello, I have already done the hard work porting this to Python 3; see my “py3” branch: <https://github.com/vadmium/grailbrowser/tree/py3>. It’s been a while since I did it, but I think it should be mainly done. Beware that my fork has a different commit history, based on the original CVS history.

**Comment by pombredanne** [comment]
@vadmium : let me make a message on my fork redirecting to yours. You seem to have a much better history and have maintained it alright.

**Pull request merged**
